--Realiza un procedimiento almacenado para insertar direcciones en la tabla
--EJEMPLO_TABLA_ANIDADA.
--• El procedimiento recibe como parámetros un identificador y un objeto
--DIRECCION. Debe visualizar un mensaje indicando si se ha insertado o no la
--dirección.
--• Se deben hacer las siguientes comprobaciones y visualizar los mensajes
--correspondientes:
--• Comprobar si el identificador existe, si no existe es un caso de error,
--visualizar el mensaje.
--• Que la tabla anidada no sea null, si no es null hay que hacer un UPDATE
--y no un INSERT.
--• Que la dirección no exista ya en la tabla, si ya existe visualiza que no se
--puede insertar.

